
@host = http://localhost:3000

GET {{host}}/api/categories

###

GET {{host}}/api/categories/2

###

PUT {{host}}/api/categories/2
content-type: application/json

{
    "name": "Foo",
    "description": "Bar"
}

###

DELETE {{host}}/api/categories/7