
@host = http://localhost:3000


### Get Categories

    GET {{host}}/api/categories

### Get Category By Id
    GET {{host}}/api/categories/2

### Update Category
    PUT {{host}}/api/categories/3
    content-type: application/json

    {
        "name": "",
        "description": "Bar"
    }

### Delete Category
    DELETE {{host}}/api/categories/22


    